spring.application.name=minilink-api
spring.datasource.url=jdbc:postgresql://localhost:5432/nome_do_seu_banco
spring.datasource.username=jose**
spring.datasource.password=jose**
spring.jpa.hibernate.ddl-auto=update
